### ISSUE TITLE
share the model code please

### ISSUE THREAD

**Issue by James4Ever0** [MrVPlusOne/vscode-coeditor#1]
i'd like to test this plugin. how could i reach you? thanks!

**Comment by MrVPlusOne** [comment]
Thanks for your interest! We'll release Coeditor for public testing soon, in the meantime, would you mind [signing up here](https://docs.google.com/forms/d/e/1FAIpQLScdDyQrpXVEJeQyov8v5g5IF0lwpi329Tn7SMEPuBJmUv1L-w/viewform?usp=sf_link)?

**Comment by MrVPlusOne** [comment]
Model has been released now! You are welcome to give it a try and share your feedback. Thanks!
